### ISSUE TITLE
Som biografgænger vil jeg kunne vælge mine sæder i biografsalen, så jeg kan reservere mine ønskede pladser.

### ISSUE THREAD

**Issue by fiepoul** [Kinoxp-organization/KinoXP-frontend#3]

**Comment by AndreaRyholt** [comment]
Accept Criteria:
- Kunne vælge dato og tidspunkt for film
- Kunne vælge et eller flere sæder på en række
- Kunne se prisen for billetterne
- Når et sæde vælges, skal det blive markeret tydeligt som "valgt".

**Comment by fiepoul** [comment]
Når et sæde vælges, skal det blive markeret tydeligt som "valgt".

**Comment by hantamil** [comment]
Story points: 3
